#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx
- name: Install nginx
  yum:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Copy nginx reverse proxy config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reload nginx
  become: true

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: true
  become: true